#环境切换
spring:
  profiles:
    active: dev       #dev 开发环境; prod 商用环境
  application:
    name: gatewayCenter  #服务注册名

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

#设置最大容错超时时间
hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 5000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
  command:
    default:
      circuitBreaker:
        foreOpen: false
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 900000

#配置admin监控内容
management:
  endpoints:
    web:
      exposure:
        include: "*"  #监控所有
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    root: info
  file:
    path: logs/