# 端口设置
server:
  port: 8002

# 注册中心与监控
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9700/eureka/eureka/
  instance:
    metadata-map:
      management:
        context-path: /user/actuator
    health-check-url: http://localhost:${server.port}/user/actuator/health
    status-page-url: http://localhost:${server.port}/user/actuator/info
    home-page-url: http://localhost:${server.port}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mcfishtest@2019
    url: "jdbc:mysql://gz-cdb-jm6bdf98.sql.tencentcdb.com:63946/db_mcfish_szl3?useUnicode=true&characterEncoding=utf8&&useSSL=false&&serverTimezone=GMT%2B8"
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 配置
    druid:
      initial-size: 1
      # 最大连接池数量
      max-active: 50
      # 最小连接池数量
      min-idle: 1
      # 获取连接时最大等待时间
      max-wait: 60000
      # 是否缓存preparedStatement，也就是PSCache。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: -1
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
      validation-query: SELECT 'x'
      # 单位：秒，检测连接是否有效的超时时间。
      validation-query-timeout: 1
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 6000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 1800000
  redis:
    sentinel:
      master: mymaster
      nodes: 132.232.148.214:26379,132.232.148.214:26380,132.232.148.214:26381
    password: hongda2019@
    lettuce:
      shutdown-timeout: 100ms #超时时间
      pool:
        max-active: 20
        min-idle: 2
        max-idle: 10
        max-wait: 500ms
    timeout: 30000
  servlet:
    multipart:
      max-file-size: 50MB  # 文件上传大小限制
      max-request-size: 50MB
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/com/macro/user/common/mapping/*.xml
  type-aliases-package: com.macro.common.entity.entity
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

jwt:  # jwt 配置
  config:
    secret: hongda