# 端口设置
server:
  port: 8002

# 注册中心与监控
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9700/eureka/eureka/
  instance:
    metadata-map:
      management:
        context-path: /user/actuator
    health-check-url: http://localhost:${server.port}/user/actuator/health
    status-page-url: http://localhost:${server.port}/user/actuator/info
    home-page-url: http://localhost:${server.port}

spring:
  datasource:
    username: root
    password: mcfishtest@2019
    url: "jdbc:mysql://gz-cdb-jm6bdf98.sql.tencentcdb.com:63946/db_mcfish_szl3?useUnicode=true&characterEncoding=utf8&&useSSL=false&&serverTimezone=GMT%2B8"
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      #连接等待超时时间
      max-wait: 30000
      #配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      #配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      #配置监控统计拦截的filters
      filter:
        #监控统计用的filter:stat
        stat:
          enabled: true
          merge-sql: true
          log-slow-sql: true
          #配置SQL慢的标准，执行时间超过slowSqlMillis的就是慢
          slow-sql-millis: 5000  #redis
  redis:
    cluster:
      nodes: 132.232.148.214:6379
    password: hongda2019@
    lettuce:
      shutdown-timeout: 100ms #超时时间
      pool:
        max-active: 20
        min-idle: 0
        max-idle: 10
        max-wait: 100ms
    timeout: 30000
  servlet:
    multipart:
      max-file-size: 50MB  # 文件上传大小限制
      max-request-size: 50MB
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/com/macro/user/common/mapping/*.xml
  type-aliases-package: com.macro.common.entity.entity
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
