#环境切换
spring:
  profiles:
    active: dev       #dev 开发环境; prod 商用环境
  application:
    name: monitorCentor  #服务注册名

# 日志设置
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

#配置admin监控内容
management:
  endpoints:
    web:
      exposure:
        include: "*"  #监控所有
  endpoint:
    health:
      show-details: always



