# 端口设置
server:
  port: 8010

# 注册中心与监控
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9700/eureka/eureka/
  instance:
    metadata-map:
      management:
        context-path: /user/actuator
    health-check-url: http://localhost:${server.port}/user/actuator/health
    status-page-url: http://localhost:${server.port}/user/actuator/info
    home-page-url: http://localhost:${server.port}

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 132.232.148.214:26379,132.232.148.214:26380,132.232.148.214:26381
    password: hongda2019@
    lettuce:
      shutdown-timeout: 100ms #超时时间
      pool:
        max-active: 20
        min-idle: 2
        max-idle: 10
        max-wait: 500ms
    timeout: 30000
  jackson:
    default-property-inclusion: non_null #空字段不返回
  servlet:
    multipart:
      max-file-size: 50MB  # 文件上传大小限制
      max-request-size: 50MB

jwt:  # jwt 配置
  config:
    secret: hongda
    expireTime: 86400000   # 24*60*60*1000 单位ms